source 'https://github.com/AAChartModel/AAChartKit-Swift.git'
# platform :ios, '12.0'

target 'bletool' do
  pod 'AAInfographics'

  use_frameworks!

  # Pods for bletool

  target 'bletoolTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'bletoolUITests' do
    # Pods for testing
  end

end
